config/routes.rb
Rails.application.routes.draw do
  get 'about/index'
  get 'welcome/index'

  resources :books, only: :index do
    get :save_to_shelf, on: :collection

  end

  root 'welcome#index'

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_resource.rb
class ApplicationResource < ActiveResource::Base
end

class ActiveResource::Base
  # Safefetch
  # Attempts to perform a nilsafe fetch of an attribute from a given active resource record.
  # @param [symbol] attribute_name
  def sfetch(attribute_name)
    self&.attributes&.fetch(attribute_name, nil)
  end
end

app/models/book.rb
class Book < ApplicationResource
  self.include_format_in_path = false
  self.collection_name = 'volumes'
  self.site = 'https://www.googleapis.com/books/v1/'

  class << self
    # Have to override where rails tries to start making its collection.  I could write a new parser for this
    # (probably safer) but in the interest of time, just going to do this for now.
    private
      def instantiate_collection(collection, original_params = {}, prefix_options = {})
        result = collection_parser.new(collection['items']).tap do |parser|
          parser.resource_class  = self
          parser.original_params = original_params
        end.collect { |record| instantiate_record(record, prefix_options) }
        result.define_singleton_method(:total_pages){50}
        result.define_singleton_method(:current_page){original_params.fetch(:startIndex, 10).to_i/10}
        result.define_singleton_method(:limit_value){10}
        result
      end
  end
end

app/models/shelf_book.rb
class ShelfBook < ApplicationResource
  self.site = Rails.application.app_config[:shelf_api_url]
  self.collection_name = 'books'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    if params&.dig('book','search')
      @books = find_books_by_name params['book']['search'], page: params['page']
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def save_to_shelf
    book_id = params[:book]
    @book = Book.find(book_id)
    shelf_book
    redirect_back fallback_location: 'index'
  end

  private
    def find_books_by_name(name, page:)
      params = {q: name, country: 'US'}
      params[:startIndex] = page.to_i*10 if page
      Book.find(:all, params: params)
    end

    def shelf_book
      @shelf_book = ShelfBook.new
      @shelf_book.title = @book.sfetch(:volumeInfo)&.sfetch(:title)
      @shelf_book.description = @book.sfetch(:volumeInfo)&.sfetch(:description)
      @shelf_book.read = false
      @shelf_book.pages_read = 0
      @shelf_book.google_id = @book.sfetch(:id)
      @shelf_book.save
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<br/>
<div class="row">
  <div class="12 Columns">Uses the following technologies</div>
  <div class="12 Columns"><a href="https://developers.google.com/books/docs/overview">Google Books API</a></div>
  <div class="12 Columns"><a href="http://materializecss.com">Materialize CSS</a></div>
  <div class="12 Columns"><a href="http://rubyonrails.org">Built with Ruby on Rails</a></div>
</div>
<div class="row">
  <div class="12 columns"><a href="http://"></a></div>
</div>

app/views/books/index.html.erb
<div class="row">
  <%= form_with scope: :book, url: books_path, id: 'book_search_form', method: :get, local: true do |form| %>
    <div class="row">
      <div class="twelve columns" id="search_section">
        <br>
        <div class="input-field col s12">
          <%= form.label :search, class: 'right' %>
          <%= form.text_field :search, id: 'book_search' %>
        </div>
        <%= form.submit 'Search Books', id: 'book_search_submit', class: 'btn waves-effect waves-light right' %>
        <img src="https://books.google.com/googlebooks/images/poweredby.png" border="0" width="62" height="30" align="absbottom" style="position: relative; top: 6px; margin:0; border: 0; padding: 0; padding-left: 8px">
      </div>
    </div>
  <% end %>
  <% if @books %>
    <%= paginate @books %>
    <div class="row" id="results_section">
      <% unless @books.to_a.nil? %>
        <% @books.each_with_index do |book, i| %>
          <div class="card horizontal" id="result_<%=i%>">
            <div class="card-image valign-wrapper">
              <img src="http://books.google.com/books/content?id=<%=book.sfetch(:id)%>&printsec=frontcover&img=1&zoom=5&edge=curl&source=gbs_api">
            </div>
            <div class="card-stacked">
              <div class="card-title"><%= book.sfetch(:volumeInfo)&.sfetch(:title) %></div>
              <div class="card-content">
                <ul class="collapsible" data-collapsible="expandable">
                  <li>
                    <div class="collapsible-header">Description</div>
                    <div class="collapsible-body"><span><%= book.sfetch(:volumeInfo)&.sfetch(:description) || 'No Description' %></span></div>
                  </li>
                </ul>
              </div>
              <div class="card-action">
                <%= link_to 'View on Google Books', book.sfetch(:volumeInfo)&.sfetch(:infoLink), class: 'waves-effect waves-light btn' %>
                <%= link_to 'Shelf It!', "#{save_to_shelf_books_path}?book=#{book.sfetch(:id)}", {class: 'waves-effect waves-light btn'} %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
    <%= paginate @books %>
<% end %>
</div>

app/views/books/show.html.erb
<div>
  <hr/>  
  <h5><%= @book.title %></h5>
  <div class="row">
    <div class="two columns right">Cover Art:</div> 
    <div class="five columns"></div>
  </div>

  <div class="row">
    <div class="two columns right">Summary:</div> 
    <div class="ten columns"><%= @book.summary %></div>
  </div>
  <hr/>
  <%= link_to 'Back to Book Listing', controller: 'books' %>
</div>

app/views/welcome/index.html.erb
<br>
A work in progress application that will query google books api and allow you to keep a listing of books that you wish
to read or have read.